nomad_version: 0.8.3
nomad_zip_archive: "nomad_{{ nomad_version }}_linux_amd64.zip"
nomad_download_path: "https://releases.hashicorp.com/nomad/{{ nomad_version }}/{{ nomad_zip_archive }}"
nomad_download_checksum: "sha256:c7faaee8fad0f6a74df01b9283253ee565f85791adca1d6a38462e0387dee175"
nomad_download_directory: "/tmp"
nomad_config_dir: "/etc/nomad.d"
nomad_data_dir: "/var/local/nomad"
nomad_home_dir: "/var/local/nomad"
nomad_log_file: "/var/log/nomad.log"
