#!/bin/bash

set -e

FILE={{ dnsmasq_general_dns_file }}

eval $(dhcpcd -T | grep new_domain_name_servers)

echo > $FILE

for server in $new_domain_name_servers; do
  echo "server=$server" >> $FILE
done
